# base image with jdk use to build and run java application
# FROM eclipse-temurin:23-jdk
FROM maven:3-eclipse-temurin-23

#labeling the dockerfile
LABEL MAINTAINER="darryl"
LABEL description="This is VTTP5 SSF Day13 lecture demo and walkthrough"
LABEL name="vttp5a-ssf-day13l"

ARG APP_DIR=/app

# directory where your source code will reside
WORKDIR ${APP_DIR}

# copy the required files into the image
COPY pom.xml .
COPY mvnw .
COPY mvnw.cmd .
COPY src src
COPY .mvn .mvn
# COPY . .

# package the application using the RUN directive
# this will download the dependencies defined in pom.xml
# compile and package to jar
RUN mvn package -Dmaven.test.skip=true

ENV SERVER_PORT=3000

EXPOSE ${SERVER_PORT}

CMD ["java", "-jar", "target/vttp5a-ssf-day13l-0.0.1-SNAPSHOT.jar"]
# ENTRYPOINT SERVER_PORT=${SERVER_PORT} java -jar target/vttp5a-ssf-day13l-0.0.1-SNAPSHOT.jar